# Generated by Django 5.2.6 on 2025-09-25 20:24

from django.db import migrations

def crear_editoriales(apps, schema_editor):
    Editorial = apps.get_model("editorial", "Editorial")
    editoriales = [
        ("Editorial Alfa", "México"),
        ("Editorial Beta", "España"),
        ("Editorial Gamma", "Argentina"),
        ("Editorial Delta", "Chile"),
        ("Editorial Epsilon", "Colombia"),
        ("Editorial Zeta", "Perú"),
        ("Editorial Omega", "Estados Unidos"),
        ("Editorial Nova", "Francia"),
        ("Editorial Prisma", "Italia"),
        ("Editorial Aurora", "Alemania"),
    ]
    for nombre, pais in editoriales:
        Editorial.objects.create(nombre=nombre, pais=pais)

class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(crear_editoriales)
    ]
