# Generated by Django 5.2.6 on 2025-09-26 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0010_alter_libro_fecha_publicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nombre')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros_autores', to='book.libro')),
            ],
        ),
    ]
