# Generated by Django 5.2.6 on 2025-09-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0001_initial'),
        ('book', '0011_alter_libro_fecha_publicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='book',
        ),
        migrations.AddField(
            model_name='autor',
            name='book',
            field=models.ManyToManyField(related_name='libros_autores', to='book.libro'),
        ),
    ]
