# Generated by Django 5.2.6 on 2025-09-25 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editorial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=70)),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='libro_editorial', to='editorial.editorial')),
            ],
        ),
    ]
