# Generated by Django 5.2.6 on 2025-09-25 20:26

from django.db import migrations

def crear_books(apps, schema_editor):
    Editorial = apps.get_model("editorial", "Editorial")
    Libro = apps.get_model("book", "Libro")

    # Buscamos las editoriales creadas
    editoriales = Editorial.objects.all()

    # Diccionario: editorial → lista de libros
    libros_por_editorial = {
        "Editorial Alfa": [
            ("9780000000001", "El Principio Alfa"),
            ("9780000000002", "La Sombra del Sol"),
        ],
        "Editorial Beta": [
            ("9780000000003", "Códigos Secretos"),
            ("9780000000004", "Más allá de Beta"),
        ],
        "Editorial Gamma": [
            ("9780000000005", "Historias Gamma"),
            ("9780000000006", "Luz y Oscuridad"),
        ],
        "Editorial Delta": [
            ("9780000000007", "Delta en el Tiempo"),
        ],
        "Editorial Epsilon": [
            ("9780000000008", "Ecos de Epsilon"),
        ],
        "Editorial Zeta": [
            ("9780000000009", "El Último Zeta"),
        ],
        "Editorial Omega": [
            ("9780000000010", "Horizontes Omega"),
        ],
        "Editorial Nova": [
            ("9780000000011", "Estrellas Nova"),
        ],
        "Editorial Prisma": [
            ("9780000000012", "Colores del Prisma"),
        ],
        "Editorial Aurora": [
            ("9780000000013", "Amanecer en Aurora"),
        ],
    }

    for editorial in editoriales:
        if editorial.nombre in libros_por_editorial:
            for isbn, titulo in libros_por_editorial[editorial.nombre]:
                Libro.objects.create(
                    isbn=isbn,
                    titulo=titulo,
                    editorial=editorial
                )

def eliminar_books(apps, schema_editor):
    Libro = apps.get_model("tu_app", "Libro")
    Libro.objects.filter(
        isbn__in=[
            "9780000000001","9780000000002","9780000000003",
            "9780000000004","9780000000005","9780000000006",
            "9780000000007","9780000000008","9780000000009",
            "9780000000010","9780000000011","9780000000012",
            "9780000000013"
        ]
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(crear_books, eliminar_books)
    ]
