# Generated by Django 5.2.6 on 2025-09-25 21:15

from django.db import migrations

def crear_mas_books(apps, schema_editor):
    Editorial = apps.get_model("editorial", "Editorial")
    Libro = apps.get_model("book", "Libro")

    # Nuevos libros por editorial (15 en total)
    nuevos_libros = {
        "Editorial Alfa": [
            ("9780000000014", "Caminos de Alfa"),
        ],
        "Editorial Beta": [
            ("9780000000015", "Secretos de Beta"),
        ],
        "Editorial Gamma": [
            ("9780000000016", "El Legado Gamma"),
        ],
        "Editorial Delta": [
            ("9780000000017", "Horizonte Delta"),
        ],
        "Editorial Epsilon": [
            ("9780000000018", "Sombras de Epsilon"),
        ],
        "Editorial Zeta": [
            ("9780000000019", "Renacer Zeta"),
        ],
        "Editorial Omega": [
            ("9780000000020", "Más allá de Omega"),
        ],
        "Editorial Nova": [
            ("9780000000021", "Nova Eterna"),
        ],
        "Editorial Prisma": [
            ("9780000000022", "Reflejos del Prisma"),
        ],
        "Editorial Aurora": [
            ("9780000000023", "Aurora Boreal"),
        ],
        # 5 más repartidos
        "Editorial Alfa": [
            ("9780000000024", "El Viaje Alfa"),
        ],
        "Editorial Beta": [
            ("9780000000025", "Beta Infinito"),
        ],
        "Editorial Gamma": [
            ("9780000000026", "Crónicas Gamma"),
        ],
        "Editorial Delta": [
            ("9780000000027", "Delta Perdido"),
        ],
        "Editorial Epsilon": [
            ("9780000000028", "Sueños de Epsilon"),
        ],
    }

    for nombre, lista in nuevos_libros.items():
        try:
            editorial = Editorial.objects.get(nombre=nombre)
            for isbn, titulo in lista:
                Libro.objects.create(isbn=isbn, titulo=titulo, editorial=editorial)
        except Editorial.DoesNotExist:
            continue

def eliminar_mas_books(apps, schema_editor):
    Libro = apps.get_model("book", "Libro")
    Libro.objects.filter(
        isbn__in=[
            "9780000000014","9780000000015","9780000000016","9780000000017","9780000000018",
            "9780000000019","9780000000020","9780000000021","9780000000022","9780000000023",
            "9780000000024","9780000000025","9780000000026","9780000000027","9780000000028",
        ]
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20250925_1426'),
    ]

    operations = [
        migrations.RunPython(crear_mas_books, eliminar_mas_books),
    ]
