# Generated by Django 5.2.6 on 2025-09-25 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20250925_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibroCalificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrellas', models.PositiveIntegerField()),
                ('calificacion', models.CharField(blank=True, max_length=70)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='libro_calificacion', to='book.libro')),
            ],
        ),
    ]
