# Generated by Django 5.2.6 on 2025-09-25 21:52

from django.db import migrations
import random

def crear_calificaciones(apps, schema_editor):
    Libro = apps.get_model("book", "Libro")
    LibroCalificacion = apps.get_model("book", "LibroCalificacion")

    # Buscar libros de la editorial con id = 1
    libros = Libro.objects.filter(editorial_id=1)

    for libro in libros:
        # Entre 3 y 4 calificaciones
        for _ in range(random.randint(3, 4)):
            LibroCalificacion.objects.create(
                libro=libro,
                estrellas=random.randint(1, 5),  # 1 a 5 estrellas
                calificacion=f"Calificación aleatoria {random.randint(1000, 9999)}"
            )


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_librocalificacion'),
    ]

    operations = [
        migrations.RunPython(crear_calificaciones)
    ]
