# Generated by Django 5.2.6 on 2025-09-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20250925_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='fecha_publicacion',
            field=models.DateField(null=True),
        ),
    ]
