# Generated by Django 5.2.6 on 2025-09-26 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_libro_fecha_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='categoria',
            field=models.CharField(default='Sexo Anal Gore Furro', max_length=50),
        ),
        migrations.AddField(
            model_name='libro',
            name='desc_corta',
            field=models.CharField(default='Sin descripción.', max_length=2000),
        ),
        migrations.AddField(
            model_name='libro',
            name='estatus',
            field=models.CharField(default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='libro',
            name='imagen',
            field=models.URLField(max_length=85, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='fecha_publicacion',
            field=models.DateField(default=datetime.datetime(2025, 9, 26, 19, 12, 45, 59884, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
