# Generated by Django 5.2.6 on 2025-09-26 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_libro_categoria_libro_desc_corta_libro_estatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='fecha_publicacion',
            field=models.DateField(default=datetime.datetime(2025, 9, 26, 19, 12, 59, 334834, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
