# Generated by Django 5.2.6 on 2025-09-26 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_alter_libro_fecha_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='fecha_publicacion',
            field=models.DateField(default=datetime.datetime(2025, 9, 26, 20, 57, 5, 866292, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
