# Generated by Django 5.2.6 on 2025-09-29 18:11

from django.db import migrations

def crear_mas_books(apps, schema_editor):
    import random
    Editorial = apps.get_model("editorial", "Editorial")
    Libro = apps.get_model("book", "Libro")
    LibroCalificacion = apps.get_model("book", "LibroCalificacion")

    libros = Libro.objects.all()
    nuevas = []
    for libro in libros:
        estrellas = random.randint(1, 10)  # entre 1 y 10
        nuevas.append(
            LibroCalificacion(
                libro=libro,
                estrellas=estrellas,
                calificacion=f"Calificación automática: {estrellas} estrellas"
            )
        )
    LibroCalificacion.objects.bulk_create(nuevas)
    print(f"Se generaron {len(nuevas)} calificaciones.")


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_alter_libro_fecha_publicacion'),
    ]

    operations = [
        migrations.RunPython(crear_mas_books)
    ]


