# Generated by Django 5.2.6 on 2025-09-29 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_auto_20250929_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='fecha_publicacion',
            field=models.DateField(default=datetime.datetime(2025, 9, 29, 18, 24, 24, 827403, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
